---
configuration:
  train_data: [
    ./tmp/dataset.csv, 
    ./tmp/dataset_Spk.csv,
    ./tmp/HH7.csv,
    ./tmp/IA7.csv,
    ./tmp/HV7.csv,
  ]
  test_data: [
    ./tmp/dataset.csv, 
    ./tmp/dataset_Spk.csv,
    ./tmp/HH7.csv,
    ./tmp/IA7.csv,
    ./tmp/HV7.csv,
  ]
  CNN_layers: [HH7, IA7, HV7]
  verbosity: 2
  epochs: 10000
  K-fold: 10
  hidden_size: 50
  min_num_points: 1
  masks: [1, 2, 3]

labels:
  label: mask
  1: [1, 1]
  2: [2, 2]
  3: [3, 3]

drop_features:
...