---
configuration:
  train_data: [./results/NN_type_class/CNN/updated_tr_thk.csv, ./data/thickness/train/thk_spk.csv]
  test_data: [./results/NN_type_class/CNN/updated_te_thk.csv, ./data/thickness/test/thk_spk.csv]
  verbosity: 2
  epochs: 10000
  K-fold: 10
  hidden_size: 15
  min_num_points: 1
  smote: False
  
drop_features:
...