---
configuration:
  train_data: [./data/rms_tr_data/aggr.csv, ./data/rms_tr_data/theta7.csv, ./data/rms_tr_data/hh7.csv, ./data/rms_tr_data/hv7.csv, ./data/rms_tr_data/theta7.csv]
  test_data: [./data/rms_te_data/aggr.csv, ./data/rms_te_data/theta7.csv, ./data/rms_te_data/hh7.csv, ./data/rms_te_data/hv7.csv, ./data/rms_te_data/theta7.csv]
  CNN_layers: [theta7, hh7, hv7]
  verbosity: 0
  epochs: 10000
  K-fold: 10
  # hidden_size: 100
  min_num_points: 50
  smote: False 
  masks: [1, 2]

drop_features:
  # - hh
  # - hv
  # - ratio
  # - c5
  # - c7
  # - c9
  # - std_hh5
  # - std_hh7
  # - std_hh9
  # - std_hv5
  # - std_hv7
  # - std_hv9
  # - theta
  # - np
...