---
configuration:
  train_data: [
    ./results/NN_thk_regr/ResNet/updated_tr_thk.csv, 
    ./data/thickness/train/thk_spk.csv,
    ./data/thickness/train/CAE_spk.csv,
    ./data/thickness/train/HH7.csv,
    ./data/thickness/train/IA7.csv,
    ./data/thickness/train/HV7.csv,
  ]
  test_data: [
    ./results/NN_thk_regr/ResNet/updated_te_thk.csv, 
    ./data/thickness/test/thk_spk.csv,
    ./data/thickness/test/CAE_spk.csv,
    ./data/thickness/test/HH7.csv,
    ./data/thickness/test/IA7.csv,
    ./data/thickness/test/HV7.csv,
  ]
  CNN_layers: [HH7, IA7, HV7]
  verbosity: 2
  epochs: 10000
  K-fold: 1
  hidden_size: 200
  min_num_points: 1
  smote: False
  
drop_features:
...