---
configuration:
  train_data: [./data/thickness/train/thk.csv, ./data/thickness/train/thk_spk.csv]
  test_data: [./data/thickness/test/thk.csv, ./data/thickness/test/thk_spk.csv]
  verbosity: 2
  epochs: 10000
  K-fold: 10
  hidden_size: 10
  min_num_points: 2
  smote: False
  
drop_features:
...