---
configuration:
  train_data: [./data/thickness/train/thk.csv, ./data/thickness/train/thk_spk.csv, ./data/thickness/train/CAE.csv]
  test_data: [./data/thickness/test/thk.csv, ./data/thickness/test/thk_spk.csv, ./data/thickness/test/CAE.csv]
  verbosity: 2
  epochs: 10000
  K-fold: 10
  # hidden_size: 100
  min_num_points: 2
  smote: False 

drop_features:
...