---
configuration:
  train_data: [./data/thickness/train/aggr_spk.csv, ./data/thickness/train/CAE_mixed.csv]
  test_data: [./data/thickness/test/aggr_spk.csv, ./data/thickness/test/CAE_mixed.csv]
  verbosity: 2
  epochs: 10000
  K-fold: 10
  # hidden_size: 100
  min_num_points: 1
  smote: False 

drop_features:
...