---
configuration:
  train_data: [./data/thk_tr_data/aggr.csv, ./data/thk_tr_data/theta7.csv, ./data/thk_tr_data/hh7_SOBEL.csv, ./data/thk_tr_data/hh7.csv, ./data/thk_tr_data/hv7.csv, ./data/thk_tr_data/hv7_SOBEL.csv, ./data/thk_tr_data/theta7.csv]
  test_data: [./data/thk_te_data/aggr.csv, ./data/thk_te_data/theta7.csv, ./data/thk_te_data/hh7_SOBEL.csv, ./data/thk_te_data/hv7.csv, ./data/thk_te_data/hv7_SOBEL.csv, ./data/thk_te_data/theta7.csv]
  CNN_layers: [theta7, hh7_SOBEL, hh7, hv7, hv7_SOBEL, theta7]
  verbosity: 2
  epochs: 1000
  K-fold: 10
  # hidden_size: 100
  min_num_points: 10
  smote: False 
...