---
configuration:
  train_data: [
    ./results/NN_type_class/CNN_spk/updated_tr_thk.csv, 
    ./data/thickness/train/thk_spk.csv, 
    ./data/thickness/train/HH7.csv,
    ./data/thickness/train/IA7.csv,
    ./data/thickness/train/HV7.csv,
  ]
  test_data: [
    ./results/NN_type_class/CNN_spk/updated_te_thk.csv, 
    ./data/thickness/test/thk_spk.csv, 
    ./data/thickness/test/HH7.csv,
    ./data/thickness/test/IA7.csv,
    ./data/thickness/test/HV7.csv,
  ]
  CNN_layers: [HH7_spk, IA7, HV7_spk]
  verbosity: 2
  epochs: 10000
  K-fold: 10
  hidden_size: 100
  min_num_points: 1
  smote: False 
  value_range: [0, 3.5]

drop_features:
...