---
configuration:
  train_data: [./data/thk_tr_data/theta_CAE.csv, ./data/thk_tr_data/aggr.csv]
  test_data: [./data/thk_te_data/theta_CAE.csv, ./data/thk_te_data/aggr.csv]
  verbosity: 0
  epochs: 10000
  K-fold: 10
  # hidden_size: 100
  min_num_points: 100
  smote: False 
...