---
configuration:
  train_data: [./results/NN_type_class/mixed/updated_tr_rms.csv, ./data/roughness/train/rms_spk.csv]
  test_data: [./results/NN_type_class/mixed/updated_te_rms.csv, ./data/roughness/test/rms_spk.csv]
  verbosity: 2
  epochs: 10000
  K-fold: 10
  hidden_size: 10
  min_num_points: 1
  smote: False
  
drop_features:
...