---
configuration:
  train_data: [./results/NN_type_class/CAE/updated_tr_aggr.csv, ./data/rms_tr_data/CAE_norm.csv]
  test_data: [./results/NN_type_class/CAE/updated_te_aggr.csv, ./data/rms_te_data/CAE_norm.csv]
  verbosity: 2
  epochs: 10000
  K-fold: 10
  # hidden_size: 100
  min_num_points: 50
  smote: False 

drop_features:
  # - hh
  # - hv
  # - ratio
  # - c5
  # - c7
  # - c9
  # - std_hh5
  # - std_hh7
  # - std_hh9
  # - std_hv5
  # - std_hv7
  # - std_hv9
  # - theta
...