---
configuration:
  train_data: [
    ./results/NN_type_class/CAE/updated_tr_rms.csv, 
    ./data/roughness/train/rms_spk.csv,
    ./data/roughness/train/HH7_canny.csv,
    ./data/roughness/train/HH7_spk.csv,
    ./data/roughness/train/HV7_spk.csv,
    ./data/roughness/train/HV7_canny.csv
  ]
  test_data: [
    ./results/NN_type_class/CAE/updated_te_rms.csv, 
    ./data/roughness/test/rms_spk.csv,
    ./data/roughness/test/HH7_canny.csv,
    ./data/roughness/test/HH7_spk.csv,
    ./data/roughness/test/HV7_spk.csv,
    ./data/roughness/test/HV7_canny.csv
  ]
  CNN_layers: [HH7_canny, HH7_spk, HV7_spk, HV7_canny]
  verbosity: 2
  epochs: 10000
  K-fold: 10
  hidden_size: 10
  min_num_points: 1
  smote: False
  
drop_features:
...