---
configuration:
  train_data: [./results/NN_type_class/CAE_spk_3C/updated_tr_rms.csv, ./data/roughness/train/rms_spk.csv, ./data/roughness/train/CAE_mixed.csv]
  test_data: [./results/NN_type_class/CAE_spk_3C/updated_te_rms.csv, ./data/roughness/test/rms_spk.csv, ./data/roughness/test/CAE_mixed.csv]
  verbosity: 2
  epochs: 10000
  K-fold: 10
  # hidden_size: 100
  min_num_points: 2
  smote: False 

drop_features:
...