---
configuration:
  train_data: [
    ./results/NN_type_class/CNN_spk/updated_tr_rms.csv, 
    ./data/roughness/train/rms_spk.csv,
    ./data/roughness/train/HH7_spk.csv,
    ./data/roughness/train/IA7.csv,
    ./data/roughness/train/HV7_spk.csv,
  ]
  test_data: [
    ./results/NN_type_class/CNN_spk/updated_te_rms.csv, 
    ./data/roughness/test/rms_spk.csv,
    ./data/roughness/test/HH7_spk.csv,
    ./data/roughness/test/IA7.csv,
    ./data/roughness/test/HV7_spk.csv,
  ]
  CNN_layers: [HH7_spk, IA7, HV7_spk]
  verbosity: 2
  epochs: 10000
  K-fold: 10
  hidden_size: 100
  min_num_points: 1
  smote: False
  value_range: [0, 200]

drop_features:
...