---
configuration:
  train_data: ./data/thk_tr_data/raw_norm.csv
  test_data: ./data/thk_te_data/raw_norm.csv
  verbosity: 2
  epochs: 10000
  K-fold: 10
  hidden_size: 30

features:
  - hh
  - hv
  - hv_hh
  - c5
  - c7
  - c9
  - std_hh5
  - std_hh7
  - std_hh9
  - std_hv5
  - std_hv7
  - std_hv9
  # - theta
  # - np
...