---
configuration:
  train_data: [./data/thk_tr_data/aggr.csv, ./data/thk_tr_data/hh7.csv, ./data/thk_tr_data/hv7.csv]
  test_data: [./data/thk_te_data/aggr.csv, ./data/thk_te_data/hh7.csv, ./data/thk_te_data/hv7.csv]
  CNN_layers: [hh7, hv7]
  verbosity: 0
  epochs: 10000
  K-fold: 10
  # hidden_size: 100
  min_num_points: 10
  smote: False 
  masks: [1, 2]
...