---
configuration:
  train_data: [./data/roughness/train/rms.csv, ./data/roughness/train/rms_spk.csv]
  test_data: [./data/roughness/test/rms.csv, ./data/roughness/test/rms_spk.csv]
  verbosity: 2
  epochs: 10000
  K-fold: 10
  hidden_size: 15
  min_num_points: 1
  smote: False
  
drop_features:
...