---
configuration:
  train_data: [./data/roughness/train/aggr_spk.csv, ./data/roughness/train/CAE_spk.csv]
  test_data: [./data/roughness/test/aggr_spk.csv, ./data/roughness/test/CAE_spk.csv]
  verbosity: 2
  epochs: 10000
  K-fold: 10
  # hidden_size: 100
  min_num_points: 1
  smote: False 

drop_features:
...