---
configuration:
  train_data: [./data/thk_tr_data/CAE.csv, ./data/thk_tr_data/aggr.csv]
  test_data: [./data/thk_te_data/CAE.csv, ./data/thk_te_data/aggr.csv]
  verbosity: 2
  epochs: 10000
  hidden_size: 30
  K-fold: 10
  min_num_points: 10
  masks: [3]

labels:
  1: [0, 2]
  2: [2, 2.5]
  3: [2.5, 3]
  4: [3, 3.5]
  5: [3.5, 4]
  6: [4, 4.5]
  7: [4.5, 5]
  8: [5, 100]

features:
  - "0"
  - "1"
  - "2"
  - "3"
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
  - "9"
  - "10"
  - "11"
  - "12"
  - "13"
  - "14"
  - "15"
  - hh
  - hv
  - ratio
  - c5
  - c7
  - c9
  - std_hh5
  - std_hh7
  - std_hh9
  - std_hv5
  - std_hv7
  - std_hv9
  - theta
  # - np
...