---
configuration:
  train_data: ./data/thk_tr_data/aggr_window.csv
  test_data: ./data/thk_te_data/aggr_window.csv
  verbosity: 2
  epochs: 10000
  K-fold: 10

labels:
  1: [0, 2]
  2: [2, 2.5]
  3: [2.5, 3]
  4: [3, 3.5]
  5: [3.5, 100]
...