---
configuration:
  smote: False
  aggregate: False
  window_size: 7
  
train_data: 
  ./data/roughness/20150418_135335.csv:
    Mask: ./data/Mask/2015_masked.tif
    SAR_data: 
      File: ./data/SAR/20150418_135335_Spk_canny.tif
      Bands:
        2: HV
    lat: 4
    lon: 5
    label: 3
    row: 7
    col: 6
  ./data/roughness/20150418_234734.csv:
    Mask: ./data/Mask/2015_masked.tif
    SAR_data: 
      File: ./data/SAR/20150418_234734_Spk_canny.tif
      Bands:
        2: HV
    lat: 4
    lon: 5
    label: 3
    row: 7
    col: 6
  ./data/roughness/20150419_132406.csv:
    Mask: ./data/Mask/2015_masked.tif
    SAR_data: 
      File: ./data/SAR/20150419_132406_Spk_canny.tif
      Bands:
        2: HV
    lat: 4
    lon: 5
    label: 3
    row: 7
    col: 6
  ./data/roughness/20150419_132521.csv:
    Mask: ./data/Mask/2015_masked.tif
    SAR_data: 
      File: ./data/SAR/20150419_132521_Spk_canny.tif
      Bands:
        2: HV
    lat: 4
    lon: 5
    label: 3
    row: 7
    col: 6
  ./data/roughness/20160409_134058.csv:
    Mask: ./data/Mask/2016_masked.tif
    SAR_data: 
      File: ./data/SAR/20160409_134058_Spk_canny.tif
      Bands:
        2: HV
    lat: 4
    lon: 5
    label: 3
    row: 7
    col: 6
  ./data/roughness/20160409_134212.csv:
    Mask: ./data/Mask/2016_masked.tif
    SAR_data: 
      File: ./data/SAR/20160409_134212_Spk_canny.tif
      Bands:
        2: HV
    lat: 4
    lon: 5
    label: 3
    row: 7
    col: 6
  ./data/roughness/20160410_131138.csv:
    Mask: ./data/Mask/2016_masked.tif
    SAR_data: 
      File: ./data/SAR/20160410_131138_Spk_canny.tif
      Bands:
        2: HV
    lat: 4
    lon: 5
    label: 3
    row: 7
    col: 6
  ./data/roughness/20180429_140506.csv:
    Mask: ./data/Mask/2018_masked.tif
    SAR_data: 
      File: ./data/SAR/20180429_140506_Spk_canny.tif
      Bands:
        2: HV
    lat: 4
    lon: 5
    label: 3
    row: 7
    col: 6
  ./data/roughness/20180429_140538.csv:
    Mask: ./data/Mask/2018_masked.tif
    SAR_data: 
      File: ./data/SAR/20180429_140538_Spk_canny.tif
      Bands:
        2: HV
    lat: 4
    lon: 5
    label: 3
    row: 7
    col: 6
  ./data/roughness/20180430_133541.csv:
    Mask: ./data/Mask/2018_masked.tif
    SAR_data: 
      File: ./data/SAR/20180430_133541_Spk_canny.tif
      Bands:
        2: HV
    lat: 4
    lon: 5
    label: 3
    row: 7
    col: 6
test_data:
  ./data/roughness/20150418_234849.csv:
    Mask: ./data/Mask/2015_masked.tif
    SAR_data: 
      File: ./data/SAR/20150418_234849_Spk_canny.tif
      Bands:
        2: HV
    lat: 4
    lon: 5
    label: 3
    row: 7
    col: 6
  ./data/roughness/20150419_231930.csv:
    Mask: ./data/Mask/2015_masked.tif
    SAR_data: 
      File: ./data/SAR/20150419_231930_Spk_canny.tif
      Bands:
        2: HV
    lat: 4
    lon: 5
    label: 3
    row: 7
    col: 6
  ./data/roughness/20160409_233615.csv:
    Mask: ./data/Mask/2016_masked.tif
    SAR_data: 
      File: ./data/SAR/20160409_233615_Spk_canny.tif
      Bands:
        2: HV
    lat: 4
    lon: 5
    label: 3
    row: 7
    col: 6
  ./data/roughness/20160410_131252.csv:
    Mask: ./data/Mask/2016_masked.tif
    SAR_data: 
      File: ./data/SAR/20160410_131252_Spk_canny.tif
      Bands:
        2: HV
    lat: 4
    lon: 5
    label: 3
    row: 7
    col: 6 
  ./data/roughness/20180429_235956.csv:
    Mask: ./data/Mask/2018_masked.tif
    SAR_data: 
      File: ./data/SAR/20180429_235956_Spk_canny.tif
      Bands:
        2: HV
    lat: 4
    lon: 5
    label: 3
    row: 7
    col: 6

output_dir:
  train_data: ./data/roughness/train/HV7_spk.csv
  test_data: ./data/roughness/test/HV7_spk.csv
...