---
configuration:
  smote: False
  aggregate: True
  window_size: 7

train_data: 
  ./data/AEM/20150419_laser_rms.csv:
    Mask: ./data/SAR/2015/2015_masked.tif
    SAR_data:
      - ./data/SAR/2015_norm/2015_hv_canny.tif
    lat: 4
    lon: 3
    label: 5
  ./data/AEM/20160408_laser_rms.csv:
    Mask: ./data/SAR/2016/2016_masked.tif
    SAR_data:
      - ./data/SAR/2016_norm/2016_hv_canny.tif
    lat: 1
    lon: 2
    label: 3
test_data: 
  ./data/AEM/20180508_laser_rms.csv:
    Mask: ./data/SAR/2018/2018_masked.tif
    SAR_data:
      - ./data/SAR/2018_norm/2018_hv_canny.tif
    lat: 4
    lon: 3
    label: 5

features:
  hv_canny: [2015_hv_canny, 2016_hv_canny, 2018_hv_canny]

output_dir:
  train_data: ./data/rms_tr_data/hv7_canny.csv
  test_data: ./data/rms_te_data/hv7_canny.csv
...