---
configuration:
  smote: False
  aggregate: True
  window_size: 7

train_data: 
  ./data/AEM/20150419_embird_thk.csv:
    Mask: ./data/SAR/2015/2015_masked.tif
    SAR_data: 
      - ./data/SAR/2015_norm/2015_hh_canny.tif
    lat: 4
    lon: 3
    label: 5
  ./data/AEM/20160408_embird_thk.csv:
    Mask: ./data/SAR/2016/2016_masked.tif
    SAR_data: 
      - ./data/SAR/2016_norm/2016_hh_canny.tif
    lat: 6
    lon: 7
    label: 9
test_data: 
  ./data/AEM/20180508_embird_thk.csv:
    Mask: ./data/SAR/2018/2018_masked.tif
    SAR_data: 
      - ./data/SAR/2018_norm/2018_hh_canny.tif
    lat: 6
    lon: 7
    label: 9

features:
  hh_canny: [2015_hh_canny, 2016_hh_canny, 2018_hh_canny]

output_dir:
  train_data: ./data/thk_tr_data/hh7_canny.csv
  test_data: ./data/thk_te_data/hh7_canny.csv
...