---
configuration:
  smote: False
  aggregate: True
  window_size: 1
  
train_data: 
  ./data/thickness/20150418_135335.csv:
    Mask: ./data/Mask/2015_masked.tif
    SAR_data: 
      File: ./data/SAR/20150418_135335_canny.tif
      Bands:
        1: HH
        2: HV
        3: IA
    lat: 4
    lon: 5
    label: 3
    row: 7
    col: 6
  ./data/thickness/20150418_234734.csv:
    Mask: ./data/Mask/2015_masked.tif
    SAR_data: 
      File: ./data/SAR/20150418_234734_canny.tif
      Bands:
        1: HH
        2: HV
        3: IA
    lat: 4
    lon: 5
    label: 3
    row: 7
    col: 6
  ./data/thickness/20150419_132406.csv:
    Mask: ./data/Mask/2015_masked.tif
    SAR_data: 
      File: ./data/SAR/20150419_132406_canny.tif
      Bands:
        1: HH
        2: HV
        3: IA
    lat: 4
    lon: 5
    label: 3
    row: 7
    col: 6
  ./data/thickness/20150419_132521.csv:
    Mask: ./data/Mask/2015_masked.tif
    SAR_data: 
      File: ./data/SAR/20150419_132521_canny.tif
      Bands:
        1: HH
        2: HV
        3: IA
    lat: 4
    lon: 5
    label: 3
    row: 7
    col: 6
  ./data/thickness/20160409_134058.csv:
    Mask: ./data/Mask/2016_masked.tif
    SAR_data: 
      File: ./data/SAR/20160409_134058_canny.tif
      Bands:
        1: HH
        2: HV
        3: IA
    lat: 4
    lon: 5
    label: 3
    row: 7
    col: 6
  ./data/thickness/20160409_134212.csv:
    Mask: ./data/Mask/2016_masked.tif
    SAR_data: 
      File: ./data/SAR/20160409_134212_canny.tif
      Bands:
        1: HH
        2: HV
        3: IA
    lat: 4
    lon: 5
    label: 3
    row: 7
    col: 6
  ./data/thickness/20160410_131138.csv:
    Mask: ./data/Mask/2016_masked.tif
    SAR_data: 
      File: ./data/SAR/20160410_131138_canny.tif
      Bands:
        1: HH
        2: HV
        3: IA
    lat: 4
    lon: 5
    label: 3
    row: 7
    col: 6
  ./data/thickness/20180429_140506.csv:
    Mask: ./data/Mask/2018_masked.tif
    SAR_data: 
      File: ./data/SAR/20180429_140506_canny.tif
      Bands:
        1: HH
        2: HV
        3: IA
    lat: 4
    lon: 5
    label: 3
    row: 7
    col: 6
  ./data/thickness/20180429_140538.csv:
    Mask: ./data/Mask/2018_masked.tif
    SAR_data: 
      File: ./data/SAR/20180429_140538_canny.tif
      Bands:
        1: HH
        2: HV
        3: IA
    lat: 4
    lon: 5
    label: 3
    row: 7
    col: 6

  ./data/thickness/20180430_133541.csv:
    Mask: ./data/Mask/2018_masked.tif
    SAR_data: 
      File: ./data/SAR/20180430_133541_canny.tif
      Bands:
        1: HH
        2: HV
        3: IA
    lat: 4
    lon: 5
    label: 3
    row: 7
    col: 6
test_data: 
  ./data/thickness/20150418_234849.csv:
    Mask: ./data/Mask/2015_masked.tif
    SAR_data: 
      File: ./data/SAR/20150418_234849_canny.tif
      Bands:
        1: HH
        2: HV
        3: IA
    lat: 4
    lon: 5
    label: 3
    row: 7
    col: 6
  ./data/thickness/20150419_231930.csv:
    Mask: ./data/Mask/2015_masked.tif
    SAR_data: 
      File: ./data/SAR/20150419_231930_canny.tif
      Bands:
        1: HH
        2: HV
        3: IA
    lat: 4
    lon: 5
    label: 3
    row: 7
    col: 6
  ./data/thickness/20160409_233615.csv:
    Mask: ./data/Mask/2016_masked.tif
    SAR_data: 
      File: ./data/SAR/20160409_233615_canny.tif
      Bands:
        1: HH
        2: HV
        3: IA
    lat: 4
    lon: 5
    label: 3
    row: 7
    col: 6
  ./data/thickness/20160410_131252.csv:
    Mask: ./data/Mask/2016_masked.tif
    SAR_data: 
      File: ./data/SAR/20160410_131252_canny.tif
      Bands:
        1: HH
        2: HV
        3: IA
    lat: 4
    lon: 5
    label: 3
    row: 7
    col: 6
  ./data/thickness/20180429_235956.csv:
    Mask: ./data/Mask/2018_masked.tif
    SAR_data: 
      File: ./data/SAR/20180429_235956_canny.tif
      Bands:
        1: HH
        2: HV
        3: IA
    lat: 4
    lon: 5
    label: 3
    row: 7
    col: 6

output_dir:
  train_data: ./data/thickness/train/rms_spk.csv
  test_data: ./data/thickness/test/rms_spk.csv
...