---
train_data: 
  - [./data/SAR/2015/2015_c5.tif, ./data/SAR/2016/2016_c5.tif]
  - [./data/SAR/2015/2015_c7.tif, ./data/SAR/2016/2016_c7.tif]
  - [./data/SAR/2015/2015_c9.tif, ./data/SAR/2016/2016_c9.tif]
  - [./data/SAR/2015/2015_hh.tif, ./data/SAR/2016/2016_hh.tif]
  - [./data/SAR/2015/2015_hv.tif, ./data/SAR/2016/2016_hv.tif]
  - [./data/SAR/2015/2015_np.tif, ./data/SAR/2016/2016_np.tif]
  - [./data/SAR/2015/2015_std_hh5.tif, ./data/SAR/2016/2016_std_hh5.tif]
  - [./data/SAR/2015/2015_std_hh7.tif, ./data/SAR/2016/2016_std_hh7.tif]
  - [./data/SAR/2015/2015_std_hh9.tif, ./data/SAR/2016/2016_std_hh9.tif]
  - [./data/SAR/2015/2015_std_hv5.tif, ./data/SAR/2016/2016_std_hv5.tif]
  - [./data/SAR/2015/2015_std_hv7.tif, ./data/SAR/2016/2016_std_hv7.tif]
  - [./data/SAR/2015/2015_std_hv9.tif, ./data/SAR/2016/2016_std_hv9.tif]
  - [./data/SAR/2015/2015_theta.tif, ./data/SAR/2016/2016_theta.tif]
  - [./data/SAR/2015/ratio.tif, ./data/SAR/2016/ratio.tif]
  - [./data/SAR/2015/2015_hh_SOBEL.tif, ./data/SAR/2016/2016_hh_SOBEL.tif]
  - [./data/SAR/2015/2015_hv_SOBEL.tif, ./data/SAR/2016/2016_hv_SOBEL.tif]

test_data: 
  - [./data/SAR/2018/2018_c5.tif]
  - [./data/SAR/2018/2018_c7.tif]
  - [./data/SAR/2018/2018_c9.tif]
  - [./data/SAR/2018/2018_hh.tif]
  - [./data/SAR/2018/2018_hv.tif]
  - [./data/SAR/2018/2018_np.tif]
  - [./data/SAR/2018/2018_std_hh5.tif]
  - [./data/SAR/2018/2018_std_hh7.tif]
  - [./data/SAR/2018/2018_std_hh9.tif]
  - [./data/SAR/2018/2018_std_hv5.tif]
  - [./data/SAR/2018/2018_std_hv7.tif]
  - [./data/SAR/2018/2018_std_hv9.tif]
  - [./data/SAR/2018/2018_theta.tif]
  - [./data/SAR/2018/ratio.tif]
  - [./data/SAR/2018/2018_hh_SOBEL.tif]
  - [./data/SAR/2018/2018_hv_SOBEL.tif]

output_dir: [./data/SAR/2015_norm, ./data/SAR/2016_norm, ./data/SAR/2018_norm]
...