---
configuration:
  train_data: ./data/rms_tr_data/aggr.csv
  test_data: ./data/rms_te_data/aggr.csv
  verbosity: 2
  epochs: 10000
  K-fold: 10
  hidden_size: 30
  min_num_points: 50

features:
  - hh
  - hv
  - hv_hh
  - c5
  - c7
  - c9
  - std_hh5
  - std_hh7
  - std_hh9
  - std_hv5
  - std_hv7
  - std_hv9
  - theta
  - np
...