---
configuration:
  train_data: [./data/rms_tr_data/hh7.csv, ./data/rms_tr_data/hv7.csv]
  test_data: [./data/rms_te_data/hh7.csv, ./data/rms_te_data/hv7.csv]
  verbosity: 2
  epochs: 10000
  K-fold: 10
  min_num_points: 10
	smote: True 
...