---
configuration:
  train_data: [./data/rms_tr_data/hh.csv, ./data/rms_tr_data/hv.csv]
  test_data: [./data/rms_te_data/hh.csv, ./data/rms_te_data/hv.csv]
  verbosity: 2
  epochs: 10000
  K-fold: 10
  min_num_points: 50
...