---
configuration:
  train_data: [./data/rms_tr_data/CAE7.csv]
  test_data: [./data/rms_te_data/CAE7.csv]
  verbosity: 2
  epochs: 10000
  K-fold: 10
  min_num_points: 50

features:
  - "0"
  - "1"
  - "2"
  - "3"
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
  - "9"
  - "10"
  - "11"
  - "12"
  - "13"
  - "14"
  - "15"
...