#!/usr/bin/env python3
import argparse
from osgeo import gdal
from sea_ice_SAR.utils import decompose_filepath


def main(args):
    output_dir, _, _ = decompose_filepath(args.hh)
    hh_ds = gdal.Open(args.hh)
    hv_ds = gdal.Open(args.hv)
    hh_band = hh_ds.GetRasterBand(1)
    hv_band = hv_ds.GetRasterBand(1)
    hh_arr = hh_band.ReadAsArray()
    hv_arr = hv_band.ReadAsArray()
    [rows, cols] = hh_arr.shape
    crosspol_ratio_arr = hv_arr / hh_arr

    driver = gdal.GetDriverByName("GTiff")
    outdata = driver.Create(f"{output_dir}/ratio.tif", cols, rows, 1, gdal.GDT_Float64)
    outdata.SetGeoTransform(hh_ds.GetGeoTransform())
    outdata.SetProjection(hh_ds.GetProjection())
    outdata.GetRasterBand(1).WriteArray(crosspol_ratio_arr)
    outdata.FlushCache()
    outdata = None
    hh_band = None
    hv_band = None
    hh_ds = None
    hv_ds = None


if __name__ == "__main__":
    parser = argparse.ArgumentParser()

    parser.add_argument(
        "--hh",
        type=str,
        help="HH polarization tif file",
    )
    parser.add_argument(
        "--hv",
        type=str,
        help="HV polarization tif file",
    )

    args = parser.parse_args()
    main(args)
