#!/usr/bin/env python3
import argparse
from sea_ice_SAR.data_processing import GLCM_handler


def main(args):
    GLCM_handler(args.input, args.img_dir)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()

    parser.add_argument("--input", type=str, help="Input csv/image file")
    parser.add_argument("--img-dir", type=str, help="Directory with raw data")

    args = parser.parse_args()
    main(args)
