#!/usr/bin/env python3
import argparse
import pandas as pd
from matplotlib import pyplot as plt
from skimage import data, io


def main(args):
    df = pd.read_csv(args.input, header=0)

    output_img = [[0 for _ in range(100)] for _ in range(100)]

    for idx, row in df.iterrows():
        output_img[row[args.row]][row[args.col]] = row[args.label]

    io.imshow(output_img)
    plt.show()


if __name__ == "__main__":
    parser = argparse.ArgumentParser()

    parser.add_argument(
        "--input",
        type=str,
        help="Input CSV",
    )
    parser.add_argument(
        "--row",
        type=str,
        help="Name of the Y column",
    )
    parser.add_argument(
        "--row",
        type=str,
        help="Name of the X column",
    )
    parser.add_argument(
        "--label",
        type=str,
        help="Name of the label column",
    )

    args = parser.parse_args()
    args = parser.parse_args()

    main(args)
