#!/usr/bin/env python3
import argparse
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
from skimage import data, io


def main(args):
    df = pd.read_csv(args.input, header=0)

    output_img = [[0 for _ in range(100)] for _ in range(100)]

    for idx, row in df.iterrows():
        y = row[args.row] - args.center[0] + 50
        x = row[args.col] - args.center[1] + 50
        if x > 0 and y > 0 and x < 99 and y < 99:
            output_img[y][x] = row[args.label]

    print(output_img)

    output_img = np.array(output_img)
    print(output_img)
    output_img = (output_img - output_img.min()) / (output_img.max() - output_img.min())

    io.imshow(output_img)
    plt.show()


if __name__ == "__main__":
    parser = argparse.ArgumentParser()

    parser.add_argument(
        "--input",
        type=str,
        help="Input CSV",
    )
    parser.add_argument(
        "--row",
        type=str,
        help="Name of the Y column",
    )
    parser.add_argument(
        "--col",
        type=str,
        help="Name of the X column",
    )
    parser.add_argument(
        "--label",
        type=str,
        help="Name of the label column",
    )
    parser.add_argument(
        "--center",
        nargs=2,
        type=int,
        help="(row, col) coorindates of the image",
    )

    args = parser.parse_args()
    args = parser.parse_args()

    main(args)
