#!/usr/bin/env python3

import argparse
import os
import pandas as pd


def main(args):
    x = int(args.x)
    y = int(args.y)

    data = []
    for row in range(100):
        for col in range(100):
            center_col, center_row = x, y
            data.append([center_row - 50 + row, center_col - 50 + col, 0, 0, 0])

    df = pd.DataFrame(data, columns=["row", "col", "label", "lat", "lon"])

    if not os.path.exists("./tmp"):
        os.makedirs("./tmp")

    df.to_csv("./tmp/base.csv", index=False)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()

    parser.add_argument(
        "--x",
        type=str,
        help="Y coordinate",
    )
    parser.add_argument(
        "--y",
        type=str,
        help="X coordinate",
    )

    args = parser.parse_args()

    main(args)
