#!/usr/bin/env python3
import argparse
import sys
import tensorflow as tf
import numpy as np
from statistics import stdev
from sea_ice_SAR.ML_tools import (
    config_parser,
    process_data,
    construct_confusion_matrix,
)
from sea_ice_SAR.utils import decompose_filepath
from sklearn.metrics import accuracy_score, classification_report
from tensorflow.keras.models import load_model

tf.get_logger().setLevel("ERROR")


def main(args):
    # Parse configuration
    _, test_data, _, _, verbosity, K, _, min_num_points, _, masks, _ = config_parser(
        args.ml_config
    )
    _, cfg_filename, _ = decompose_filepath(args.ml_config)

    log_file = open(f"{args.result_dir}/{cfg_filename}/test.log", "w")
    sys.stdout = log_file

    # Modify test dataset
    X_te, _, Y_te, classes = process_data(
        test_data,
        args.ml_config,
        regression=False,
        min_num_points=min_num_points,
        masks=masks,
    )

    accuracy_li = []
    for k in range(K):
        print(
            f"*************************** Fold #: {k+1} ***************************",
            file=sys.stdout,
        )
        # Call checkpoint
        checkpoint_path = f"{args.result_dir}/{cfg_filename}/ckpt_{k+1}"
        trained_model = load_model(checkpoint_path)

        # Predict the test dataset
        y_pred = np.argmax(
            trained_model.predict(x=X_te, batch_size=1000, verbose=verbosity), axis=1
        )
        accuracy = accuracy_score(Y_te, y_pred)
        accuracy_li.append(accuracy)
        print(f"Test accuracy: {accuracy}", file=sys.stdout)
        print(classification_report(Y_te, y_pred), file=sys.stdout)

        # Construct confusion matrix
        construct_confusion_matrix(
            classes, Y_te, y_pred, f"{args.result_dir}/{cfg_filename}", k
        )

    print(f"\nMaximum accuracy: {max(accuracy_li)}", file=sys.stdout)
    print(f"\nAverage accuracy: {sum(accuracy_li)/K}", file=sys.stdout)
    print(f"Standard Deviation (accuracy): {stdev(accuracy_li)}", file=sys.stdout)

    # stdout redirection closed
    log_file.close()


if __name__ == "__main__":
    parser = argparse.ArgumentParser()

    parser.add_argument(
        "--result-dir",
        type=str,
        help="Directory path with train results including checkpoint files",
    )
    parser.add_argument(
        "--ml-config",
        nargs="+",
        type=str,
        help="YAML file containing the configuration for deep learning",
    )

    args = parser.parse_args()
    if type(args.ml_config) == list:
        ml_configs = args.ml_config[:]
        for ml_config in ml_configs:
            args.ml_config = ml_config
            main(args)
    else:
        main(args)
