#!/usr/bin/env python3
import argparse


def main():
    None


if __name__ == "__main__":
    parser = argparse.ArgumentParser()

    parser.add_argument(
        "--input-dir",
        type=str,
        help="Directory containing imagest to be upscaled",
    )

    args = parser.parse_args()
    main(args)
