---
configuration:
  train_data: [./data/rms_tr_data/aggr.csv, ./data/rms_tr_data/theta7.csv, ./data/rms_tr_data/hh7_canny.csv, ./data/rms_tr_data/hh7.csv, ./data/rms_tr_data/hv7.csv, ./data/rms_tr_data/hv7_canny.csv, ./data/rms_tr_data/theta7.csv]
  test_data: [./data/rms_te_data/aggr.csv, ./data/rms_te_data/theta7.csv, ./data/rms_te_data/hh7_canny.csv, ./data/rms_te_data/hv7.csv, ./data/rms_te_data/hv7_canny.csv, ./data/rms_te_data/theta7.csv]
  CNN_layers: [theta7, hh7_canny, hh7, hv7, hv7_canny, theta7]
  verbosity: 2
  epochs: 1000
  K-fold: 10
  # hidden_size: 100
  min_num_points: 50
  smote: False 
  masks: [3]
...