---
configuration:
  train_data: [./data/roughness/train/rms.csv, ./data/roughness/train/rms_spk.csv]
  test_data: [./data/roughness/test/rms.csv, ./data/roughness/test/rms_spk.csv]
  epochs: 10000
  verbosity: 2
  K-fold: 10
  hidden_size: 15
  min_num_points: 1
  masks: [1, 2, 3]

labels:
  label: mask
  1: [1, 2]
  2: [3, 3]

drop_features:
...