---
configuration:
  train_data: ./data/thk_tr_data/aggr.csv
  test_data: ./data/thk_te_data/aggr.csv
  epochs: 10000
  verbosity: 0
  K-fold: 10
  # hidden_size: 100
  min_num_points: 10
  masks: [1, 2, 3]

labels:
  label: mask
  1: [1, 2]
  2: [3, 3]

drop_features:
  # - hh
  # - hv
  # - ratio
  - c5
  - c7
  - c9
  - std_hh5
  - std_hh7
  - std_hh9
  - std_hv5
  - std_hv7
  - std_hv9
  # - theta
...