---
configuration:
  train_data: [./data/thickness/train/thk.csv, ./data/thickness/train/thk_spk.csv]
  test_data: [./data/thickness/test/thk.csv, ./data/thickness/test/thk_spk.csv]
  epochs: 10000
  verbosity: 0
  K-fold: 10
  # hidden_size: 100
  min_num_points: 1
  masks: [1, 2, 3]

labels:
  label: mask
  1: [1, 1]
  2: [2, 2]
  3: [3, 3]

drop_features:
...