---
configuration:
  train_data: [./data/thk_tr_data/aggr.csv, ./data/thk_tr_data/CAE.csv]
  test_data: [./data/thk_te_data/aggr.csv, ./data/thk_te_data/CAE.csv]
  verbosity: 0
  epochs: 10000
  K-fold: 10
  # hidden_size: 100
  min_num_points: 10
  masks: [1, 2, 3]

labels:
  label: mask
  1: [1, 2]
  2: [3, 3]
...