---
configuration:
  train_data: [./data/thickness/train/aggr.csv, ./data/thickness/train/CAE.csv]
  test_data: [./data/thickness/test/aggr.csv, ./data/thickness/test/CAE.csv]
  verbosity: 2
  epochs: 10000
  K-fold: 10
  # hidden_size: 100
  min_num_points: 1
  masks: [1, 2, 3]

labels:
  label: mask
  1: [1, 2]
  2: [3, 3]

drop_features:
...