---
configuration:
  train_data: [
    ./data/roughness/train/rms.csv, 
    ./data/roughness/train/rms_spk.csv,
    ./data/roughness/train/HH7_canny.csv,
    ./data/roughness/train/HH7.csv,
    ./data/roughness/train/HV7.csv,
    ./data/roughness/train/HV7_canny.csv
  ]
  test_data: [
    ./data/roughness/test/rms.csv, 
    ./data/roughness/test/rms_spk.csv,
    ./data/roughness/test/HH7_canny.csv,
    ./data/roughness/test/HH7.csv,
    ./data/roughness/test/HV7.csv,
    ./data/roughness/test/HV7_canny.csv
  ]
  CNN_layers: [HH7_canny, HH7, HV7, HV7_canny]
  verbosity: 2
  epochs: 10000
  K-fold: 10
  hidden_size: 50
  min_num_points: 1
  masks: [1, 2, 3]

labels:
  label: mask
  1: [1, 1]
  2: [2, 2]
  3: [3, 3]

drop_features:
...