---
configuration:
  train_data: [./data/thk_tr_data/aggr.csv, ./data/thk_tr_data/SOBEL_CAE.csv]
  test_data: [./data/thk_te_data/aggr.csv, ./data/thk_te_data/SOBEL_CAE.csv]
  verbosity: 2
  epochs: 10000
  K-fold: 10
  # hidden_size: 100
  min_num_points: 10
  smote: True 
...