---
configuration:
  train_data: ./data/rms_tr_data/aggr_GLCM_norm.csv
  test_data: ./data/rms_te_data/aggr_GLCM_norm.csv
  verbosity: 2
  epochs: 10000
  K-fold: 10
  # hidden_size: 100
  min_num_points: 50
  smote: False 
  masks: [1, 2]
...