---
train_dir: ./data/thickness/train
test_dir: ./data/thickness/test
filenames: [HH7_canny, HH7, HV7, HV7_canny]
new_features: [HH7_canny, HH7, HV7, HV7_canny]
epochs: 1000
output_filename: CAE
min_num_points: 1
verbosity: 2
...