---
train_dir: ./data/thk_tr_data
test_dir: ./data/thk_te_data
filenames: [hh7_canny, theta7, hh7, hv7, theta7, hv7_canny]
new_features: [hh7_canny, theta7, hh7, hv7, theta7, hv7_canny]
epochs: 10000
output_filename: canny_CAE
min_num_points: 10
verbosity: 2
...