---
train_dir: ./data/thk_tr_data
test_dir: ./data/thk_te_data
filenames: [hh7_SOBEL, hh7, hv7, hv7_SOBEL]
new_features: [hh7_SOBEL, hh7, hv7, hv7_SOBEL]
epochs: 1000
output_filename: SOBEL_CAE
min_num_points: 10
...